/**
 * Admin panel tests.
 *
 * The panel writes two kinds of file that the build then reads: .env for
 * settings, and JavaScript modules for posts. Both are generated by string
 * assembly, which is exactly where escaping bugs live — a stray backtick in
 * an article title would produce a module that does not parse, and a quote in
 * an ad snippet would truncate the value silently.
 *
 * These tests drive the real HTTP API against a temporary copy of the blog
 * directory, so nothing here touches the actual content.
 */

const test = require("node:test");
const assert = require("node:assert");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");

const env = require("../src/lib/env.js");

const ROOT = path.join(__dirname, "..");

/* ------------------------------------------------------------------ *
 * .env round-tripping
 * ------------------------------------------------------------------ */

test("env: a plain value round-trips", () => {
  const text = env.stringify({ SITE_URL: "https://example.com" });
  assert.deepStrictEqual(env.parse(text), { SITE_URL: "https://example.com" });
});

test("env: values containing spaces are quoted and survive", () => {
  const value = "adsterra.com, 1234567, DIRECT";
  const parsed = env.parse(env.stringify({ ADS_TXT: value }));
  assert.strictEqual(parsed.ADS_TXT, value);
});

test("env: an ad snippet with quotes round-trips exactly", () => {
  // This is the realistic case: Adsterra banner code contains double quotes,
  // single quotes and angle brackets.
  const snippet =
    `<script type="text/javascript">atOptions = {'key':'abc123','format':'iframe'};</script>` +
    `<script src="//www.highperformanceformat.com/abc123/invoke.js"></script>`;

  const parsed = env.parse(env.stringify({ ADS_BANNER: snippet }));
  assert.strictEqual(parsed.ADS_BANNER, snippet);
});

test("env: a multi-line snippet round-trips", () => {
  const snippet = `<script>\n  atOptions = { key: 'x' };\n</script>\n<script src="//x.test/i.js"></script>`;
  const parsed = env.parse(env.stringify({ ADS_BANNER: snippet }));
  assert.strictEqual(parsed.ADS_BANNER, snippet);
});

test("env: backslashes survive the round trip", () => {
  const value = 'a\\b\\\\c';
  assert.strictEqual(env.parse(env.stringify({ K: value })).K, value);
});

test("env: comments and blank lines are ignored", () => {
  const parsed = env.parse(`
# a comment
SITE_URL=https://example.com

  # indented comment
CONTACT_EMAIL=me@example.com
`);
  assert.deepStrictEqual(parsed, {
    SITE_URL: "https://example.com",
    CONTACT_EMAIL: "me@example.com"
  });
});

test("env: the shell 'export' prefix is tolerated", () => {
  assert.strictEqual(env.parse("export SITE_URL=https://x.com").SITE_URL, "https://x.com");
});

test("env: malformed lines are skipped rather than throwing", () => {
  const parsed = env.parse("GOOD=1\nnot a variable\n=missing key\n123BAD=x\nALSO_GOOD=2");
  assert.deepStrictEqual(parsed, { GOOD: "1", ALSO_GOOD: "2" });
});

test("env: an empty value stays empty rather than becoming a string", () => {
  assert.strictEqual(env.parse(env.stringify({ ADS_BANNER: "" })).ADS_BANNER, "");
});

/* ------------------------------------------------------------------ *
 * load() must never override a real environment variable
 * ------------------------------------------------------------------ */

test("env: load does not overwrite variables already in the environment", () => {
  const file = path.join(os.tmpdir(), `tp-env-${Date.now()}`);
  fs.writeFileSync(file, "TP_TEST_KEY=from-file\nTP_TEST_OTHER=also-from-file\n");

  process.env.TP_TEST_KEY = "from-environment";
  delete process.env.TP_TEST_OTHER;

  try {
    env.load(file);
    // A deployment secret must always win over a stray local file.
    assert.strictEqual(process.env.TP_TEST_KEY, "from-environment");
    assert.strictEqual(process.env.TP_TEST_OTHER, "also-from-file");
  } finally {
    delete process.env.TP_TEST_KEY;
    delete process.env.TP_TEST_OTHER;
    fs.unlinkSync(file);
  }
});

test("env: a missing file is not an error", () => {
  assert.deepStrictEqual(env.load(path.join(os.tmpdir(), "definitely-not-here-xyz")), {});
});

/* ------------------------------------------------------------------ *
 * The panel's HTTP API
 * ------------------------------------------------------------------ */

/** Boots admin.js on a free port, in a sandbox that has its own blog dir. */
async function startPanel() {
  const port = 9000 + Math.floor(Math.random() * 900);
  const sandbox = fs.mkdtempSync(path.join(os.tmpdir(), "tp-admin-"));

  // Work on a copy so the real articles and .env are never touched.
  fs.cpSync(path.join(ROOT, "src"), path.join(sandbox, "src"), { recursive: true });
  fs.cpSync(path.join(ROOT, "scripts"), path.join(sandbox, "scripts"), { recursive: true });
  fs.cpSync(path.join(ROOT, "package.json"), path.join(sandbox, "package.json"));

  const { spawn } = require("node:child_process");
  const child = spawn(process.execPath, [path.join(sandbox, "scripts", "admin.js")], {
    env: { ...process.env, ADMIN_PORT: String(port), ADMIN_HOST: "127.0.0.1" },
    stdio: "pipe"
  });

  // Wait for it to accept connections.
  const base = `http://127.0.0.1:${port}`;
  for (let i = 0; i < 60; i++) {
    try {
      await fetch(`${base}/api/status`);
      break;
    } catch {
      await new Promise(r => setTimeout(r, 100));
    }
  }

  return {
    base,
    sandbox,
    stop() {
      child.kill();
      fs.rmSync(sandbox, { recursive: true, force: true });
    },
    async get(route) {
      const res = await fetch(`${base}/api/${route}`);
      return { status: res.status, data: await res.json() };
    },
    async post(route, body) {
      const res = await fetch(`${base}/api/${route}`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body)
      });
      return { status: res.status, data: await res.json() };
    },
    async del(route) {
      const res = await fetch(`${base}/api/${route}`, { method: "DELETE" });
      return { status: res.status, data: await res.json() };
    }
  };
}

test("admin: serves the panel UI", async () => {
  const panel = await startPanel();
  try {
    const res = await fetch(panel.base + "/");
    assert.strictEqual(res.status, 200);
    const html = await res.text();
    assert.match(html, /ToolPeak Admin/);
  } finally {
    panel.stop();
  }
});

test("admin: reports status without any settings configured", async () => {
  const panel = await startPanel();
  try {
    const { data } = await panel.get("status");
    assert.strictEqual(typeof data.posts, "number");
    assert.strictEqual(data.tools, 10);
    assert.ok(Array.isArray(data.adsConfigured));
  } finally {
    panel.stop();
  }
});

test("admin: settings save to .env and read back identically", async () => {
  const panel = await startPanel();
  try {
    const snippet = `<script type="text/javascript">atOptions = {'key' : 'k1'};</script>`;

    const saved = await panel.post("settings", {
      SITE_URL: "https://example.github.io",
      ADS_BANNER: snippet,
      ADS_TXT: "adsterra.com, 999, DIRECT"
    });
    assert.strictEqual(saved.status, 200);

    const { data } = await panel.get("settings");
    assert.strictEqual(data.values.SITE_URL, "https://example.github.io");
    assert.strictEqual(data.values.ADS_BANNER, snippet);
    assert.strictEqual(data.values.ADS_TXT, "adsterra.com, 999, DIRECT");
  } finally {
    panel.stop();
  }
});

test("admin: the settings file it writes is a valid .env the build can read", async () => {
  const panel = await startPanel();
  try {
    const snippet = `<script src="//pl1.profitableratecpm.com/a.js"></script>`;
    await panel.post("settings", { ADS_POPUNDER: snippet, SITE_URL: "https://x.test" });

    const written = fs.readFileSync(path.join(panel.sandbox, ".env"), "utf8");
    const parsed = env.parse(written);

    assert.strictEqual(parsed.ADS_POPUNDER, snippet);
    assert.strictEqual(parsed.SITE_URL, "https://x.test");
  } finally {
    panel.stop();
  }
});

test("admin: creates a post that is valid, requirable JavaScript", async () => {
  const panel = await startPanel();
  try {
    const { status, data } = await panel.post("post", {
      title: "A Panel Test Article",
      description: "Checking the panel writes a module the build can load.",
      keywords: "test",
      date: "2026-11-01",
      related: ["word-counter"],
      body: "<p>Hello.</p>",
      faqs: [{ q: "Q1?", a: "A1." }]
    });

    assert.strictEqual(status, 200);
    assert.strictEqual(data.slug, "a-panel-test-article");

    const file = path.join(panel.sandbox, "src", "content", "blog", "a-panel-test-article.js");
    const post = require(file);

    assert.strictEqual(post.title, "A Panel Test Article");
    assert.deepStrictEqual(post.related, ["word-counter"]);
    assert.strictEqual(post.faqs.length, 1);
    // A bare answer should be wrapped so the FAQ markup stays consistent.
    assert.strictEqual(post.faqs[0].a, "<p>A1.</p>");
  } finally {
    panel.stop();
  }
});

test("admin: escapes backticks and template syntax in the body", async () => {
  const panel = await startPanel();
  try {
    // Post bodies are written into a template literal. An unescaped backtick
    // or ${...} would produce a file that throws on require, or silently
    // interpolate something.
    const body = "<p>A backtick ` and ${braces} and a backslash \\ here.</p>";

    await panel.post("post", {
      title: "Escaping Check",
      description: "x",
      body,
      faqs: []
    });

    const file = path.join(panel.sandbox, "src", "content", "blog", "escaping-check.js");
    const post = require(file);

    assert.strictEqual(post.body.trim(), body);
  } finally {
    panel.stop();
  }
});

test("admin: escapes quotes in the title", async () => {
  const panel = await startPanel();
  try {
    const title = 'The "Best" Way to Save 50% \\ More';
    await panel.post("post", { title, description: "x", body: "<p>y</p>", faqs: [] });

    const files = fs.readdirSync(path.join(panel.sandbox, "src", "content", "blog"));
    const created = files.find(f => f.startsWith("the-best-way"));
    assert.ok(created, "the post should have been created");

    const post = require(path.join(panel.sandbox, "src", "content", "blog", created));
    assert.strictEqual(post.title, title);
  } finally {
    panel.stop();
  }
});

test("admin: refuses to overwrite an existing post unless asked", async () => {
  const panel = await startPanel();
  try {
    const payload = { title: "Duplicate Guard", description: "x", body: "<p>one</p>", faqs: [] };

    const first = await panel.post("post", payload);
    assert.strictEqual(first.status, 200);

    const second = await panel.post("post", payload);
    assert.strictEqual(second.status, 409);
    assert.match(second.data.error, /already exists/);

    const third = await panel.post("post", { ...payload, body: "<p>two</p>", overwrite: true });
    assert.strictEqual(third.status, 200);
    assert.strictEqual(third.data.updated, true);
  } finally {
    panel.stop();
  }
});

test("admin: rejects a post with no title or no body", async () => {
  const panel = await startPanel();
  try {
    const noTitle = await panel.post("post", { title: "", body: "<p>x</p>" });
    assert.strictEqual(noTitle.status, 400);

    const noBody = await panel.post("post", { title: "Has a title", body: "  " });
    assert.strictEqual(noBody.status, 400);
  } finally {
    panel.stop();
  }
});

test("admin: lists posts with word and FAQ counts", async () => {
  const panel = await startPanel();
  try {
    const { data } = await panel.get("posts");
    assert.ok(data.posts.length >= 12, "the real articles should be listed");
    assert.strictEqual(data.tools.length, 10);

    const post = data.posts[0];
    assert.ok(typeof post.words === "number" && post.words > 0);
    assert.ok(typeof post.faqs === "number");
  } finally {
    panel.stop();
  }
});

test("admin: loads a post for editing and deletes it", async () => {
  const panel = await startPanel();
  try {
    await panel.post("post", {
      title: "Round Trip", description: "x", body: "<p>content</p>",
      faqs: [{ q: "Q?", a: "<p>A.</p>" }]
    });

    const loaded = await panel.get("post?slug=round-trip");
    assert.strictEqual(loaded.status, 200);
    assert.strictEqual(loaded.data.post.title, "Round Trip");

    const deleted = await panel.del("post?slug=round-trip");
    assert.strictEqual(deleted.status, 200);

    const gone = await panel.get("post?slug=round-trip");
    assert.strictEqual(gone.status, 404);
  } finally {
    panel.stop();
  }
});

/* ------------------------------------------------------------------ *
 * Ad checking through the API
 * ------------------------------------------------------------------ */

test("admin: checks a snippet without saving it", async () => {
  const panel = await startPanel();
  try {
    const legacy = `<script type="text/javascript">
atOptions = {'key':'5f51499447a3ee41e0dd09f11ce139c7','format':'iframe','height':90,'width':728,'params':{}};
document.write('<scr' + 'ipt src="http' + (location.protocol === 'https:' ? 's' : '') + '://www.highperformanceformat.com/5f51499447a3ee41e0dd09f11ce139c7/invoke.js"></scr' + 'ipt>');
</script>`;

    const { status, data } = await panel.post("ads/check", { ADS_BANNER: legacy });
    assert.strictEqual(status, 200);

    const banner = data.per.banner;
    assert.ok(banner.rewritten, "the safe rewrite should be offered");
    assert.ok(banner.warnings.some(w => /document\.write/.test(w)));

    // Checking must not write anything.
    assert.ok(!fs.existsSync(path.join(panel.sandbox, ".env")),
      "checking a snippet should not save it");
  } finally {
    panel.stop();
  }
});

test("admin: reports the ads.txt line alongside the snippets", async () => {
  const panel = await startPanel();
  try {
    const { data } = await panel.post("ads/check", { ADS_TXT: "adsterra.com 123 DIRECT" });
    assert.ok(data.adsTxt.errors.length > 0, "a malformed record should be caught");
  } finally {
    panel.stop();
  }
});

test("admin: verify reports nothing built before a build runs", async () => {
  const panel = await startPanel();
  try {
    // The sandbox has no dist/.
    const { data } = await panel.get("ads/verify");
    assert.strictEqual(data.built, false);
    assert.match(data.reason, /No build yet/);
  } finally {
    panel.stop();
  }
});

test("admin: verify reads the ad payload out of a built page", async () => {
  const panel = await startPanel();
  try {
    // A page whose payload contains braces inside the snippet values — the
    // shape that defeats a naive regex and made this report a false negative.
    const dist = path.join(panel.sandbox, "dist", "tools");
    fs.mkdirSync(dist, { recursive: true });
    fs.writeFileSync(path.join(panel.sandbox, "dist", "index.html"), "<html></html>");

    const payload = JSON.stringify({
      popunder: "",
      socialBar: "",
      banner: `<script>atOptions = {'key':'k','params':{}};</script>`
    });
    fs.writeFileSync(
      path.join(dist, "word-counter.html"),
      `<html><body><div class="adslot" data-ad="banner"></div>
       <script>window.__TP_ADS=${payload};</script></body></html>`
    );
    fs.writeFileSync(path.join(panel.sandbox, "dist", "ads.txt"), "adsterra.com, 1, DIRECT\n");

    const { data } = await panel.get("ads/verify");

    assert.strictEqual(data.built, true);
    assert.strictEqual(data.units.banner, true, "the banner payload should be seen");
    assert.strictEqual(data.units.popunder, false);
    assert.strictEqual(data.bannerSlot, true);
    assert.strictEqual(data.adsTxt.present, true);
    assert.deepStrictEqual(data.problems, []);
  } finally {
    panel.stop();
  }
});

test("admin: verify notices settings that have not been built yet", async () => {
  const panel = await startPanel();
  try {
    const dist = path.join(panel.sandbox, "dist");
    fs.mkdirSync(dist, { recursive: true });
    fs.writeFileSync(path.join(dist, "index.html"),
      `<html><body><script>window.__TP_ADS={"popunder":"","socialBar":"","banner":""};</script></body></html>`);

    await panel.post("settings", {
      ADS_POPUNDER: `<script src="//pl1.profitableratecpm.com/a.js"></script>`
    });

    const { data } = await panel.get("ads/verify");
    assert.strictEqual(data.stale, true);
    assert.ok(data.problems.some(p => /Rebuild/.test(p)),
      "saving without rebuilding is the easiest way to think ads are live when they are not");
  } finally {
    panel.stop();
  }
});

/* ------------------------------------------------------------------ *
 * The panel must never become part of the deployed site
 * ------------------------------------------------------------------ */

test("admin: the panel is not copied into the build output", () => {
  const dist = path.join(ROOT, "dist");
  if (!fs.existsSync(dist)) return;

  const files = [];
  const walk = dir => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) walk(full);
      else files.push(path.relative(dist, full));
    }
  };
  walk(dist);

  for (const file of files) {
    assert.ok(!/admin/i.test(file), `${file} should not be in the published site`);
  }
});

test("admin: the panel UI has no truncated inline script", () => {
  // An HTML parser ends an inline script at the first literal closing tag it
  // finds, even inside a string or a comment. Writing one while describing ad
  // code silently cuts the rest of the panel's JavaScript off, and the page
  // still loads — just half-dead. This broke the Ads tab once already.
  const html = fs.readFileSync(path.join(ROOT, "scripts", "admin-ui.html"), "utf8");

  const open = html.indexOf("<script>");
  const close = html.indexOf("</script>", open);

  assert.ok(open !== -1, "the panel should have an inline script");
  assert.ok(
    close > html.length - 200,
    "the inline script is cut short — something before offset " + close +
    " contains a literal closing script tag that should be escaped"
  );
});

test("admin: the panel UI parses and boots without errors", async () => {
  const { JSDOM, VirtualConsole } = require("jsdom");
  const html = fs.readFileSync(path.join(ROOT, "scripts", "admin-ui.html"), "utf8");

  const errors = [];
  const vc = new VirtualConsole();
  vc.on("jsdomError", e => errors.push(e.message));

  const dom = new JSDOM(html, {
    runScripts: "dangerously",
    url: "http://localhost:8081/",
    virtualConsole: vc,
    beforeParse(w) {
      // No server here: answer every call with an empty but well-shaped body.
      w.fetch = async url => {
        const route = String(url).replace("/api/", "");
        const reply = data => ({ ok: true, json: async () => data });
        if (route === "status") {
          return reply({ posts: 0, tools: 0, adsConfigured: [], adsTxtSet: false, siteUrl: "", distBuilt: false });
        }
        if (route === "posts") return reply({ posts: [], tools: [] });
        if (route === "settings") return reply({ schema: [], values: {}, fromEnvironment: [] });
        return reply({});
      };
    }
  });

  await new Promise(r => setTimeout(r, 400));

  const document = dom.window.document;
  for (const tab of ["dash", "ads", "posts", "write", "settings"]) {
    assert.ok(document.querySelector(`#tab-${tab}`), `the ${tab} tab button should exist`);
    assert.ok(document.querySelector(`#pane-${tab}`), `the ${tab} pane should exist`);
  }

  assert.deepStrictEqual(errors, [], "the panel should boot without script errors");
  dom.window.close();
});

test("admin: binds to localhost by default", () => {
  // There is no authentication, and the panel can read ad snippets. Defaulting
  // to 0.0.0.0 would expose them to anyone on the network.
  const source = fs.readFileSync(path.join(ROOT, "scripts", "admin.js"), "utf8");
  assert.match(source, /ADMIN_HOST\s*\|\|\s*"127\.0\.0\.1"/,
    "the admin panel must default to localhost");
});
